### ISSUE TITLE
Save button in library not working

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#415]
Trying to update some information in the library - the 'save' button' is greyed out even after an edit to an existing measure is made so doesn't seem to do anything. If you click on it nothing happens. If you close the window any changes made aren't saved. Means we currently can't edit the library. 
<img width="1319" alt="Screen Shot 2019-05-22 at 07 53 57" src="https://user-images.githubusercontent.com/16305707/58153700-a0a2a480-7c67-11e9-8ac4-037f920f42ae.png">

**Comment by cagabi** [comment]
I have fixed this but it's not a final fix.
The problem was linked to #344, as described in that issue we implemented 2 ways of showing a library to edit:

1. Items are shown in rows, makes more sense as a growing library will grow vertically but it's difficult to compare fields
2. Items are shown in columns, easier to compare fields but the modal window grows with the amount of items in the library

I first implemented 1 including the saving functionality. But as 2 was only temporary I didn't implement the saving functionality. I am happy to do it but ideally I would prefer to clarify how we want to show the libraries.
So for the time being we are showing the Heating system library again by rows and the saving works.
I keep this issue open but change it to Medium priority

**Comment by marianneURBED** [comment]
Hi Carlos, 
I think the libraries as a whole need a review - which will be done in the next month. 
However in the meantime we still need to save edits and additions to the library and the heating measures library is still not allowing me to save. Can you have a look at this? I just get a message saying there was a problem saving in this library (was trying to edit some info on a heatpump for Andrew to use).

**Comment by cagabi** [comment]
I can save my Standard library for Heating Measures.
Can you please share the one you are having problems with me?

**Comment by marianneURBED** [comment]
Hi Carlos, 
It was the Carbon Coop library - but it seems to be working now. 
Previously the 'save' button appeared to be completely greyed out, but functioning now. Will close this issue now.
